### ISSUE TITLE
Move Webpack minify out of its own config and into the main config

### ISSUE THREAD

**Issue by jasonbarone** [Squarefront/squarespace-template-helper#10]
When initially running `npm start` the second webpack config is running first, then re-running after initial build. The whole minification process should probably be moved into the main config and run as part of a single webpack process similar to how the CSS is setup now.

**Comment by mwickett** [comment]
Do you mean the `plugin:` section of `webpack.config.js` starting on line 107?

**Comment by jasonbarone** [comment]
Not entirely sure where the minification process should go yet. I kind of like how the CSSNano minify is running so I want to get the JS minify into that somehow. UglifyJS is the tool needed,

**Comment by jasonbarone** [comment]
Pushed some updates in https://github.com/Squarefront/squarespace-template-helper/commit/73ba6ded905b34efe1f953b1a36bd650e54e1f39 that cleans up, simplifies, and speeds up Webpack. So far I'm really happy with the speed increase.
