### ISSUE TITLE
Unexpected Identifier Error - Breaks ImageLoader

### ISSUE THREAD

**Issue by mwickett** [Squarefront/squarespace-template-helper#4]
I've included `app.js` in my `site.region` file without making any changes to it (just to get jQuery on my project) and am getting an Unexpected Identifier Error. I've tested by excluding all non-template JS (nothing else custom). The error occurs when I include `app.js` and isn't present when I exclude it.

I'm honestly out of my league troubleshooting this any further, but wanted to bring it to your attention. 

```
JSC_PARSE_ERROR. Parse error. invalid property id at combo line 1819 : 79
JSC_PARSE_ERROR. Parse error. missing name after . operator at combo line 1835 : 27
JSC_PARSE_ERROR. Parse error. missing name after . operator at combo line 1836 : 34
JSC_PARSE_ERROR. Parse error. missing name after . operator at combo line 8752 : 21
JSC_PARSE_ERROR. Parse error. syntax error at combo line 8753 : 16
JSC_PARSE_ERROR. Parse error. missing ) after argument list at combo line 8772 : 1
JSC_PARSE_ERROR. Parse error. syntax error at combo line 8772 : 7
JSC_PARSE_ERROR. Parse error. syntax error at combo line 8775 : 8
JSC_PARSE_ERROR. Parse error. syntax error at combo line 8778 : 14
JSC_PARSE_ERROR. Parse error. syntax error at combo line 8779 : 6
JSC_PARSE_ERROR. Parse error. syntax error at combo line 8781 : 14
JSC_PARSE_ERROR. Parse error. syntax error at combo line 8782 : 6
JSC_PARSE_ERROR. Parse error. syntax error at combo line 8783 : 7
JSC_PARSE_ERROR. Parse error. syntax error at combo line 8784 : 10
JSC_PARSE_ERROR. Parse error. syntax error at combo line 8785 : 9
JSC_PARSE_ERROR. Parse error. syntax error at combo line 8786 : 14
JSC_PARSE_ERROR. Parse error. syntax error at combo line 8787 : 8
JSC_PARSE_ERROR. Parse error. syntax error at combo line 8788 : 14
JSC_PARSE_ERROR. Parse error. syntax error at combo line 8801 : 10
JSC_PARSE_ERROR. Parse error. syntax error at combo line 8802 : 7
JSC_PARSE_ERROR. Parse error. syntax error at combo line 8803 : 8
JSC_PARSE_ERROR. Parse error. syntax error at combo line 8804 : 8
JSC_PARSE_ERROR. Parse error. syntax error at combo line 8805 : 7
JSC_PARSE_ERROR. Parse error. syntax error at combo line 8806 : 8
JSC_PARSE_ERROR. Parse error. syntax error at combo line 8807 : 4
JSC_PARSE_ERROR. Parse error. syntax error at combo line 8809 : 11
JSC_PARSE_ERROR. Parse error. syntax error at combo line 8810 : 7
JSC_PARSE_ERROR. Parse error. illegal character at combo line 8810 : 10
JSC_PARSE_ERROR. Parse error. illegal character at combo line 8810 : 11
JSC_PARSE_ERROR. Parse error. missing } after function body at combo line 8810 : 11
JSC_PARSE_ERROR. Parse error. unterminated regular expression literal at combo line 8810 : 17
JSC_PARSE_ERROR. Parse error. syntax error at combo line 8811 : 8
JSC_PARSE_ERROR. Parse error. illegal character at combo line 8811 : 11
JSC_PARSE_ERROR. Parse error. syntax error at combo line 8811 : 18
JSC_PARSE_ERROR. Parse error. syntax error at combo line 8812 : 8
JSC_PARSE_ERROR. Parse error. illegal character at combo line 8812 : 11
JSC_PARSE_ERROR. Parse error. illegal character at combo line 8812 : 12
```

I'm not sure how to get my hands on the combo-ed file, but I can grab it if it helps.

**Comment by jasonbarone** [comment]
Hey @mwickett I had a typo in the webpack config for the Webpack expose loader, which exposes jQuery to the window object. Pushed fix, try that and we'll reopen if it's still causing problems.

**Comment by mwickett** [comment]
I did some more poking around, and here's what I found:

With the changes you made, everything works (except for what I think is a missing function in the custom jQuery build, see below) when `app.js` and my custom script (the quiz) **aren't** combo'd. When they are, I see the same parse error.

So, clearly (I think...) there's something in the template scripts that are conflicting. The template in question here is [Bryler](http://bryler-demo.squarespace.com)

### Missing jQuery function in custom build
When using the jQuery build included in `app.js`, I get `$(...).outerWidth is not a function` flagged against [this line of the quiz code](https://github.com/justmarkup/jquery-personality-quiz/blob/master/src/jquery.juma-quiz.js#L49)

I don't get it when using a full CDN version of jQuery.

**Comment by jasonbarone** [comment]
Oh ok, I think it's possible that your jQuery script might require an older version of jquery or that it might use some methods that I was stripping out. In order to test that, run this jquery build instead. Since you've already built it once, you can basically just cd into the jquery folder and run the grunt build again.

```
cd js/lib/jquery

grunt build
```

That should give you a complete jquery build. Try that first and see if that helps.

**Comment by jasonbarone** [comment]
Oh, and afterwards you of course have to build the root project again using `npm start` or `npm run build`.

**Comment by mwickett** [comment]
Yeah, it needed a full jQuery build. Worked fine. 

Does the combo vs no combo thing make sense to you?

**Comment by jasonbarone** [comment]
@mwickett I've had multiple issues in the past of problems coming from comboing with Squarespace. So it's hard to say what might be causing that. The best thing I can suggest is to not combo **your custom stuff**. Squarespace's combo feature is mainly geared towards those simple scenarios when you're not using a build system and doing complex stuff. If you start getting into using a custom JavaScript setup like the template helps with, you'll probably end up NOT using their combo feature anymore. For instance, nearly every site I do now looks like below. This repo also has a `npm run min:js` task which will create a minified version for you too.

Here's what's in the footer of my template:

```
        {.if authenticatedAccount}
            <squarespace:script src="app.js" />
        {.or}
            <squarespace:script src="app.min.js" />
        {.end}
        {squarespace-footers}
    </body>
</html>
```

**Comment by mwickett** [comment]
Thanks for clarifying around the combo issues - I was kind of stuck on keeping everything combo'd, but it doesn't actually matter (with minified app.js etc.)
