### ISSUE TITLE
Set cssnano to safe mode?

### ISSUE THREAD

**Issue by mwickett** [Squarefront/squarespace-template-helper#9]
Looks like cssnano is crushing things like `z-index: 5000` to `z-index: 1` because it rebases by default, but because this css is running on top of Squarespaces built-in stuff, it doesn't know about it.

Should be a simple change of adding `options.safe` to `true` in webpack config.

**Comment by mwickett** [comment]
I read into the docs a bit further and full safe mode might be overkill (throwing away some useful optimizations).

Could change `safe: true` to `zindex: false` on [line 107](https://github.com/Squarefront/squarespace-template-helper/blob/master/webpack.config.js#L115)

I've tested this and it works.

**Comment by jasonbarone** [comment]
I'll take a look and probably come up with a recommended set of options. Sounds like Safe Mode will be defaulted on cssnano 4.0: https://github.com/ben-eb/cssnano/issues/88.
